/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "export.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(TemporaryExposureKeyExport, TemporaryExposureKeyExport, AUTO)


PB_BIND(SignatureInfo, SignatureInfo, AUTO)


PB_BIND(TemporaryExposureKey, TemporaryExposureKey, AUTO)


PB_BIND(TEKSignatureList, TEKSignatureList, AUTO)


PB_BIND(TEKSignature, TEKSignature, AUTO)




